### PR TITLE
Added degrees class for Colleges.

### PR DESCRIPTION
**Pull request by Korbrent**
Still trying to wrap my head around the Spring framework, but did some minor changes to the Colleges classes so that degrees offered is no longer a list of Strings, but rather a custom Degrees data type. 

Benefits of Degree type
- Allow us to give required credits to attain degree
- Level of Degree (Master, Bachelor, etc)
- Name of Degree
- Will later allow us to search and sort for colleges that offer certain degrees (ex. "Criminal Justice - Doctorate")

### CODE REVIEW

**Review by ENoll78 — APPROVED** [review]
Let's think of using the degrees/majors that Colleges list they have as selectable from a menu on Frontend, so we don't have 5000+ people trying to input "Computer Science", "CompSci", "CS", etc

**Comment by meta1203** [comment]
@Korbrent This is a really nit-picky thing to bring up, but I'd prefer to call the class name `Degree` vs `Degrees`, as the class only encapsulates a single degree.

**Comment by Korbrent** [comment]
> @Korbrent This is a really nit-picky thing to bring up, but I'd prefer to call the class name `Degree` vs `Degrees`, as the class only encapsulates a single degree.

Alright, will update commit after my class rn.

**Review by Korbrent — COMMENTED** [review]
@meta1203 Nitpicking completed. 

Pull me in, Scotty!

**Pull request merged**
