### PR TITLE
POST /college

### PR DESCRIPTION
**Pull request by meta1203**
also created a testing class

### CODE REVIEW

**Comment by meta1203** [comment]
@Korbrent got the following error when running tests:

```
Validation failed for classes [com.collegecompendium.backend.models.College] during persist time for groups [jakarta.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=auth0Id, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=url, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=email, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=location, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=lastName, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
	ConstraintViolationImpl{interpolatedMessage='must not be empty', propertyPath=username, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotEmpty.message}'}
	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=firstName, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=username, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
]
```

**Comment by Korbrent** [comment]
> @Korbrent got the following error when running tests:
> 
> ```
> Validation failed for classes [com.collegecompendium.backend.models.College] during persist time for groups [jakarta.validation.groups.Default, ]
> List of constraint violations:[
> 	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=auth0Id, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
> 	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=url, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
> 	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=email, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
> 	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=location, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
> 	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=lastName, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
> 	ConstraintViolationImpl{interpolatedMessage='must not be empty', propertyPath=username, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotEmpty.message}'}
> 	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=firstName, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
> 	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=username, rootBeanClass=class com.collegecompendium.backend.models.College, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
> ]
> ```

I removed the test for now.

**Review by ENoll78 — APPROVED** [review]
Got to this late; looks good.

**Comment by ENoll78** [comment]
Or maybe I didn't miss this. I'm turned around: Was this what you were adding/talking about last night?

**Comment by Korbrent** [comment]
> Or maybe I didn't miss this. I'm turned around: Was this what you were adding/talking about last night?

I just removed the test cases so it would pass until we're ready to add in College unit testing

**Pull request merged**
